name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Create a GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Create a GitHub Release (Fails if release already exists with same version number)
        uses: actions/github-script@v6
        env:
          package-version: ${{ steps.package-version.outputs.current-version }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v' + process.env['package-version'],
              generate_release_notes: true,
            });
